name = "Lucon"
uuid = "ee70d37e-021e-48ac-98f1-58dad3ba901e"
authors = ["Tobias Schäfer"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
